### ISSUE TITLE
entering vehicles

### ISSUE THREAD

**Issue by VanniMartino** [legofreak107/VehiclePlus#4]
When I enter a vehicle, it will not move forward, back, left or right. It doesn't display the HUD where the mph and fuel is located. Is there a fix for this?

**Comment by legofreak107** [comment]
You need to have protocollib and vault installed.
And you need to make sure you are running the correct version of Minecraft.

**Comment by VanniMartino** [comment]
Im running 1.14.4 and have both protocollib and cault installed, still doesn't work.

**Comment by VanniMartino** [comment]
I reinstalled the latest versions of both, now I can't even enter the vehicle.

**Comment by VanniMartino** [comment]
Im sorry for being an idiot, my version of spigot was out of date. Please forgive my inconvenience.
